"""Initial schema: configurations, simulations, artifacts

Revision ID: 013af7207755
Revises:
Create Date: 2025-10-28 04:18:20.582315

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '013af7207755'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('data_blob', sa.LargeBinary(), nullable=True),
    sa.Column('data_path', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_hash_name', 'artifacts', ['params_hash', 'name'], unique=False)
    op.create_index(op.f('ix_artifacts_params_hash'), 'artifacts', ['params_hash'], unique=False)
    op.create_table('configurations',
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('params_hash')
    )
    op.create_index(op.f('ix_configurations_params_hash'), 'configurations', ['params_hash'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('data_format', sa.String(length=20), nullable=False),
    sa.Column('data_blob', sa.LargeBinary(), nullable=True),
    sa.Column('data_path', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_kind'), 'simulations', ['kind'], unique=False)
    op.create_index('ix_simulations_kind_hash', 'simulations', ['kind', 'params_hash'], unique=False)
    op.create_index(op.f('ix_simulations_params_hash'), 'simulations', ['params_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_params_hash'), table_name='simulations')
    op.drop_index('ix_simulations_kind_hash', table_name='simulations')
    op.drop_index(op.f('ix_simulations_kind'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_configurations_params_hash'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_artifacts_params_hash'), table_name='artifacts')
    op.drop_index('ix_artifacts_hash_name', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
